export const GET_MONTHLY_CHART_DATA = 'GET_MONTHLY_CHART_DATA';
export const GET_DAILY_CHART_DATA = 'GET_DAILY_CHART_DATA';
export const GET_BIG_CHART_DATA = 'GET_BIG_CHART_DATA';
export const GET_STATS = 'GET_STATS';
export const GET_REFERALS = 'GET_REFERALS';
export const GET_LOGS = 'GET_LOGS';
